# vi: ft=config
tap "heroku/brew"
tap "homebrew/cask"
tap "thoughtbot/formulae"

brew "asdf"
brew "fish"
brew "fzf"
brew "git"
brew "heroku/brew/heroku"
brew "hub"
brew "imagemagick"
brew "neovim"
brew "the_silver_searcher"
brew "thoughtbot/formulae/rcm"

cask "kitty"
cask "visual-studio-code"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
cask "android-studio"
