# ~/.tmuxinator/general.yml

name: <%= args[0] %>
root: <%= args[1] %>
pre_window: clear

windows:
  - editor:
      layout: b392,208x57,0,0{80x57,0,0,10,127x57,81,0,12}
      panes:
        -
        - vim
  - utils:
      panes:
        -
