# ~/.tmuxinator/general.yml

name: <%= args[0] %>
root: <%= args[1] %>
pre_window: clear

windows:
  - editor:
      layout: 4341,283x57,0,0{78x57,0,0,17,204x57,79,0,19}
      panes:
        -
        - vim
  - utils:
      layout: d2e8,283x57,0,0{78x57,0,0[78x28,0,0,54,78x28,0,29,56],204x57,79,0,57}
      panes:
        -
        -
        -
