abbr c "clear"
abbr vim "nvim"
abbr vr "nvim +KittySpawnRunner"
abbr yr "yarn run"
abbr nr "npm run"
abbr be "bundle exec"
abbr rcup "RCRC=~/.dotfiles/config/rcrc rcup"

alias g="hub"
alias git="hub"
