abbr c "clear"
abbr cat "bat"
abbr rcup "RCRC=~/.dotfiles/config/rcrc rcup"
abbr spectrum "set_color --print-colors"
abbr vim "nvim"
abbr yr "yarn run"

alias be="bundle exec"
alias g="hub"
alias git="hub"
alias yr="yarn run"
