abbr c "clear"
abbr spectrum "set_color --print-colors"
abbr vim "nvim"
abbr yr "yarn run"
abbr nr "npm run"
abbr be "bundle exec"
abbr rcup "RCRC=~/.dotfiles/config/rcrc rcup"

alias g="hub"
alias git="hub"
